# Generated by Django 5.2 on 2025-04-28 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='site',
            field=models.URLField(blank=True, null=True),
        ),
    ]
