# Generated by Django 5.2 on 2025-04-28 08:47

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_shop_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('shops', models.ManyToManyField(related_name='product_categories', to='backend.shop')),
            ],
            options={
                'verbose_name': 'Product category',
                'verbose_name_plural': 'Product categories',
            },
            managers=[
                ('categories', django.db.models.manager.Manager()),
            ],
        ),
    ]
