# Generated by Django 5.2 on 2025-04-28 09:39

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_names', to='backend.category')),
            ],
            options={
                'verbose_name': 'Product name',
                'verbose_name_plural': 'Product names',
            },
            managers=[
                ('products', django.db.models.manager.Manager()),
            ],
        ),
    ]
