# Generated by Django 5.2 on 2025-04-28 12:01

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product model', 'verbose_name_plural': 'Product model'},
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_models', to='backend.category'),
        ),
        migrations.CreateModel(
            name='ProductInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('rrp', models.DecimalField(decimal_places=2, max_digits=12)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_info', to='backend.product')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_info', to='backend.shop')),
            ],
            options={
                'verbose_name': 'Product info',
                'verbose_name_plural': 'Products info',
            },
            managers=[
                ('products_info', django.db.models.manager.Manager()),
            ],
        ),
    ]
