# Generated by Django 5.2 on 2025-04-28 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_product_options_alter_product_category_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Model',
        ),
    ]
