# Generated by Django 5.2 on 2025-04-28 18:06

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_parameter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parameter',
            options={'verbose_name': 'Product name', 'verbose_name_plural': 'Product names'},
        ),
        migrations.AlterField(
            model_name='parameter',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='ProductParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.parameter')),
                ('product_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.productinfo')),
            ],
            options={
                'verbose_name': 'Product parameter',
                'verbose_name_plural': 'Product parameters',
            },
            managers=[
                ('product_parameters', django.db.models.manager.Manager()),
            ],
        ),
    ]
