# Generated by Django 5.2 on 2025-04-29 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_contact'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='category',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='contact',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='model',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='order',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='orderitem',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='parameter',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='productinfo',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='productparameter',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='shop',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='type',
            field=models.CharField(choices=[('PHONE', 'phone number'), ('EMAIL', 'email')], default='EMAIL', max_length=5),
        ),
    ]
