# Generated by Django 5.2 on 2025-04-30 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_alter_category_name_alter_model_name_alter_shop_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parameter',
            options={'verbose_name': 'Parameter name', 'verbose_name_plural': 'Parameter names'},
        ),
    ]
