# Generated by Django 5.2 on 2025-05-03 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_alter_parameter_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinfo',
            name='product_name',
            field=models.CharField(),
        ),
    ]
