# Generated by Django 5.2 on 2025-06-10 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_deliveryaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Created'), (1, 'Confirmed'), (2, 'Paid'), (3, 'Processing'), (4, 'Dispatched'), (5, 'In Transit'), (6, 'Delivered'), (7, 'Cancelled')], default=0),
        ),
    ]
